#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

setxkbmap -layout us,ru -option grp:alt_space_toggle &
picom --config ~/.config/picom/picom.conf &
$HOME/.fehbg &
$HOME/.config/polybar/launch.sh &
xsetroot -cursor_name left_ptr &
xinput --set-prop 9 'libinput Accel Speed' -0.6 &
$HOME/.config/dunst/launch.sh &
nm-applet --indicator &
lxpolkit &
$HOME/.set-microphone.sh &
brave https://calendar.google.com/calendar/u/0/r/month &
brave https://mail.utoronto.ca &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize

bspc rule -a zoom state=floating desktop='^5'
bspc rule -a zoom:zoom:Chat layer=above desktop='^5'
bspc rule -a "VirtualBox Manager" state=floating

if !(ps aux | grep xidlehook | grep -v grep > /dev/null)
then
    xidlehook --not-when-audio --not-when-fullscreen --timer 300 "betterlockscreen -l dimblur --off 15" "" &
fi

if !(ps aux | grep blueman-applet | grep -v grep > /dev/null)
then
    blueman-applet &
fi

if !(ps aux | grep redshift | grep -v grep > /dev/null)
then
    redshift -l 55.7558:37.6173 &
fi

if !(ps aux | grep discord | grep -v grep > /dev/null && ps aux | grep mailspring | grep -v grep > /dev/null)
then
    dex -a -s /etc/xdg/autostart/:~/.config/autostart &
fi

